### PR TITLE
forms.SchemaField.to_python(): check if value already has a target type

### PR DESCRIPTION
**Pull request by alexey-sveshnikov**
Hi Savva!

Thank you for the great library! I enjoy using it a lot.

This is a small fix to a problem I encountered after upgrading to v2. I think the patch is pretty much self-explanatory, except for the case which is triggered the bug. It was in a django-constance custom fields config:

```python
CONSTANCE_ADDITIONAL_FIELDS = {
    'my_field_type': [
        'django_pydantic_field.v2.forms.SchemaField', {
            'schema': MyModelName,
        }
    ]
}

CONSTANCE_CONFIG = {
    'MY_FIELD': ({}, '...', 'my_field_type'),
}
```

### CODE REVIEW

**Comment by surenkov** [comment]
Hi @alexey-sveshnikov, thanks for bringing this up!

I could imagine how this cand be a problem with the form, but this particular case is a bit elusive for me -- I haven't had any setup with `django-constance`, so may I kindly ask you a bit of the detail, like stack trace for example, for historical reasons, as it may be useful for `django-pydantic-field` users.

Another point that I want to put into consideration, is that it's not always the case that validation schema is `pydantic.BaseModel`. The field can accept arbitrary annotation as long as it is acceptable by pydantic itself, and checking against `isinstance(..., BaseModel)` may not solve the issue entirely. 
Maybe slightly reversing the condition here, and perform the parsing only if the incoming data is a string which is not a `JSONString`, otherwise try to adapt the data with `adapter.validate_python` could work more correct, but that needs to be tested against several cases.

**Comment by surenkov** [comment]
@alexey-sveshnikov based on the assumptions above, I prepared [this PR](https://github.com/alexey-sveshnikov/django-pydantic-field/pull/1) to your base branch.

These changes are published to PyPI [under 0.3.2b1 pre-release](https://pypi.org/project/django-pydantic-field/0.3.2b1/) -- I would be glad if you can try them against your configuration to test if that would work...

**Comment by alexey-sveshnikov** [comment]
Thank you.

I've added `bytes` to the condition as well.

> stack trace for example, for historical reasons, as it may be useful for django-pydantic-field users.

I actually have no stack traces. The exception I got was ValidationError and it has been handled like normal validation error (`Schema didn't match for MyModel`)

**Comment by alexey-sveshnikov** [comment]
0.3.2b1 works fine with django-constance!

**Comment by surenkov** [comment]
Great, thank you! I'll add the test cases for `bytes` and prepare the next patch for PyPI.

**Pull request merged**
